# Generated by Django 3.1.7 on 2021-04-24 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('id_type', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('rg_weight', models.IntegerField(blank=True, null=True)),
                ('awg_weight', models.IntegerField(blank=True, null=True)),
                ('ex_id', models.CharField(blank=True, max_length=12, null=True)),
                ('upd_time', models.DateTimeField(blank=True, null=True)),
                ('ar_get', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Auto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Auto_brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auto_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('passport_mass', models.IntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, db_column='auto_brands', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.auto_brands')),
            ],
            options={
                'db_table': 'Auto_model',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='QodexUser',
        ),
        migrations.AddField(
            model_name='auto',
            name='auto_model',
            field=models.ForeignKey(blank=True, db_column='auto_model', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.auto_model'),
        ),
    ]
