# Generated by Django 3.1.7 on 2021-04-24 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210424_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFID_ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'RFID_ID',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='rfid_id',
            field=models.ForeignKey(blank=True, db_column='rfid_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rfid_id'),
        ),
    ]
