# Generated by Django 3.1.7 on 2021-04-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_weight_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash_cats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(blank=True, null=True)),
                ('ex_id', models.IntegerField(blank=True, null=True)),
                ('ar_get', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Trash_cats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trash_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('ex_id', models.IntegerField(blank=True, null=True)),
                ('ar_get', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trash_cats')),
            ],
            options={
                'db_table': 'Trash_types',
                'managed': True,
            },
        ),
    ]
