# Generated by Django 3.1.7 on 2021-04-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trash_cats_trash_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qodex_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('last_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('weight_fault', models.IntegerField(blank=True, null=True)),
                ('connected', models.BooleanField(blank=True, null=True)),
                ('inn', models.CharField(blank=True, max_length=20, null=True)),
                ('kpp', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Qodex_user',
                'managed': True,
            },
        ),
    ]
