# Generated by Django 3.1.7 on 2021-04-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_qodex_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='poligon',
            field=models.ForeignKey(blank=True, db_column='poligon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.qodex_users'),
        ),
        migrations.AddField(
            model_name='trash_cats',
            name='poligon',
            field=models.ForeignKey(blank=True, db_column='poligon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.qodex_users'),
        ),
        migrations.AddField(
            model_name='trash_types',
            name='poligon',
            field=models.ForeignKey(blank=True, db_column='poligon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.qodex_users'),
        ),
        migrations.AlterModelTable(
            name='qodex_users',
            table='Qodex_users',
        ),
    ]
