# Generated by Django 3.1.7 on 2021-04-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210424_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qodex_org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('inn', models.CharField(blank=True, max_length=10, null=True)),
                ('kpp', models.CharField(blank=True, max_length=20, null=True)),
                ('adress', models.CharField(blank=True, max_length=200, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('dirrector', models.CharField(blank=True, max_length=60, null=True)),
                ('org_type', models.CharField(blank=True, max_length=30, null=True)),
                ('date_lic', models.DateTimeField(blank=True, null=True)),
                ('lic_status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Qodex_org',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User_roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Qodex_achive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('origin', models.TextField(blank=True, null=True)),
                ('new_data', models.TextField(blank=True, null=True)),
                ('restored', models.BooleanField(blank=True, null=True)),
                ('restored_date', models.DateTimeField(blank=True, null=True)),
                ('poligon', models.ForeignKey(blank=True, db_column='poligon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.qodex_users')),
            ],
            options={
                'db_table': 'Qodex_achive',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
                ('fullname', models.CharField(blank=True, max_length=30, null=True)),
                ('ex_id', models.IntegerField(blank=True, null=True)),
                ('upd_time', models.DateTimeField(blank=True, null=True)),
                ('ar_get', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('poligon', models.ForeignKey(blank=True, db_column='poligon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.qodex_users')),
            ],
            options={
                'db_table': 'Operators',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cm_events_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('event', models.IntegerField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=12, null=True)),
                ('ex_id', models.IntegerField(blank=True, null=True)),
                ('upd_time', models.DateTimeField(blank=True, null=True)),
                ('poligon', models.ForeignKey(blank=True, db_column='poligon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.qodex_users')),
            ],
            options={
                'db_table': 'Cm_events_log',
                'managed': True,
            },
        ),
    ]
