# Generated by Django 3.1.7 on 2021-04-25 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cm_events_log_operators_qodex_achive_qodex_org_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Regions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RFID_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'RFID_types',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='qodex_users',
            name='qodex_org',
            field=models.ForeignKey(blank=True, db_column='qodex_org', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.qodex_org'),
        ),
        migrations.AddField(
            model_name='qodex_users',
            name='role',
            field=models.ForeignKey(blank=True, db_column='user_roles', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user_roles'),
        ),
        migrations.AddField(
            model_name='rfid_id',
            name='owner_id',
            field=models.ForeignKey(blank=True, db_column='qodex_users', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.qodex_users'),
        ),
        migrations.CreateModel(
            name='Oro_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_fault', models.IntegerField(blank=True, null=True)),
                ('oro', models.ForeignKey(blank=True, db_column='oro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.qodex_users')),
            ],
            options={
                'db_table': 'Oro_info',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='qodex_org',
            name='region',
            field=models.ForeignKey(blank=True, db_column='region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.regions'),
        ),
        migrations.AddField(
            model_name='qodex_users',
            name='region',
            field=models.ForeignKey(blank=True, db_column='regions', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.regions'),
        ),
        migrations.AddField(
            model_name='rfid_id',
            name='rfid_type',
            field=models.ForeignKey(blank=True, db_column='rfid_types', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rfid_types'),
        ),
    ]
